<?xml version="1.0"?>
<package format="2">
  <name>dataspeed_rostest</name>
  <version>0.1.4</version>
  <description>
    Utilities for making ros tests
  </description>

  <license>Proprietary</license>
  <author email="llorenz@dataspeedinc.com">Lincoln Lorenz</author>
  <maintainer email="llorenz@dataspeedinc.com">Lincoln Lorenz</maintainer>
  <url type="website">http://dataspeedinc.com</url>
  <url type="repository">https://bitbucket.org/dataspeedinc/drive_by_wire</url>
  <url type="bugtracker">https://bitbucket.org/dataspeedinc/drive_by_wire/issues</url>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>

</package>
